server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Tabooxie/TabooCloudConfig.git
          username: tabooxie@163.com
          password: Nirvina123!




