server:
  port: 80

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001:7001/eureka/, http://eureka7002:7002/eureka/, http://eureka7003:7003/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: App_Consumer

